# Generated by Django 5.1.1 on 2024-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students_bca',
            fields=[
                ('studentrolln', models.IntegerField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=200)),
                ('studentmarks', models.IntegerField()),
                ('studentresult', models.CharField(max_length=100)),
            ],
        ),
    ]
